export const HELP = [
  {
    CMD: 'cd',
    TEXT: 'Change directory',
    CONTENT: '현재 작업 디렉터리의 위치를 바꾸는 명령어입니다.',
    EXAMPLE: 'cd ../home',
    ICON: '👉',
  },
  {
    CMD: 'clear',
    TEXT: 'Clear terminal',
    CONTENT: '터미널을 깨끗하게 지웁니다.',
    EXAMPLE: 'clear',
    ICON: '🧹',
  },
  {
    CMD: 'cp',
    TEXT: 'Copy file',
    CONTENT: '파일을 복사하는 명령어입니다.',
    EXAMPLE: 'cp file1 file2',
    ICON: '📝',
  },
  {
    CMD: 'help',
    TEXT: 'List all commands',
    CONTENT: '모든 명령어를 나열합니다. 한번 쳐보세요.',
    EXAMPLE: 'help',
    ICON: '🤗',
  },
  {
    CMD: 'mkdir',
    TEXT: 'Create directory',
    CONTENT: '디렉터리를 생성합니다.',
    EXAMPLE: 'mkdir directory',
    ICON: '📂',
  },
  {
    CMD: 'mv',
    TEXT: 'Move file',
    CONTENT: '파일을 이동합니다.',
    EXAMPLE: 'mv file1 file2',
    ICON: '🚚',
  },
  {
    CMD: 'pwd',
    TEXT: 'Print working directory',
    CONTENT: '현재 작업 디렉터리의 위치를 출력합니다.',
    EXAMPLE: 'pwd',
    ICON: '📌',
  },
  {
    CMD: 'rm',
    TEXT: 'Remove file',
    CONTENT: '파일을 삭제합니다.',
    EXAMPLE: 'rm file',
    ICON: '🗑',
  },
  {
    CMD: 'touch',
    TEXT: 'Create file',
    CONTENT: '파일을 생성합니다.',
    EXAMPLE: 'touch file',
    ICON: '📄',
  },
];
